### ISSUE TITLE
Correctly show total additions and deletions after sync.

### ISSUE THREAD

**Issue by lemoer** [byro/byro-mailman#2]
https://github.com/byro/byro-mailman/blob/5c49cde08a5100236bb05fbd31f9ff590b789d44/byro_mailman/views.py#L79-L85

I guess, it should be 
```
 stats = _('There were {} additions and {} deletions in total.').format(*total) 
```

**Comment by rixx** [comment]
Released in v1.0.1. Thank you for the patch!
